export const MY_ADVERTISEMENTS_ACTIVE_TAB = 'Active';
export const MY_ADVERTISEMENTS_PENDING_TAB = 'Pending';
export const MY_ADVERTISEMENTS_INACTIVE_TAB = 'Inactive';
export const MY_ADVERTISEMENTS_TABS: string[] = [
  MY_ADVERTISEMENTS_ACTIVE_TAB,
  MY_ADVERTISEMENTS_PENDING_TAB,
  MY_ADVERTISEMENTS_INACTIVE_TAB,
];
